### ISSUE TITLE
Migrations are broken

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1458]
I feel like I'm reading over some obvious typo or misconfig here, so I'm posting in the hopes someone spots it.

Build is failing: https://github.com/lobsters/lobsters/actions/runs/13169060376/job/36755813576

I can't run tests because it complains that `db/migrate/20250203223624_count_merged_stories.rb` hasn't run. The `stories.stories_count` column that migration creates exists, as does a `20250203223624` in `schema_migrations`.

If I run `db:migrate` I get this failure:

```
$ r db:migrate
W, [2025-02-05T18:21:46.655004 #1098250]  WARN -- : heinous_inline_partial initialized, found: {"app/views/comments/_threads.html.erb" => "app/views/comments/_comment.html.erb", "app/views/home/index.html.erb" => "app/views/stories/_listdetail.html.erb", "app/views/search/index.html.erb" => "app/views/stories/_listdetail.html.erb"}
bin/rails aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: near "SHOW": syntax error: (ActiveRecord::StatementInvalid)
SHOW FULL TABLES WHERE table_type = "VIEW"
^


Caused by:
SQLite3::SQLException: near "SHOW": syntax error: (SQLite3::SQLException)
SHOW FULL TABLES WHERE table_type = "VIEW"
^

Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

Which is weird, it looks like it's trying to run mariadb commands against sqlite, though I have my dev and test envs configured to use mariabdb.

```
---
trilogy: &trilogy
  adapter: trilogy
  encoding: utf8mb4
  host: 127.0.0.1
  port: 3306
  pool: 5
  socket: /run/mysqld/mysqld.sock
  username: pushcx
  password: [redacted]

sqlite3: &sqlite3
  adapter: sqlite3
  timeout: 1000

development:
  primary:
    <<: *trilogy
    database: lobsters
  cache:
    <<: *sqlite3
    database: tmp/cache/cache.sqlite3
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *trilogy
    database: lobsters_test
  cache:
    <<: *sqlite3
    database: tmp/cache/cache.sqlite3
    migrations_paths: db/cache_migrate

production:
  primary:
    <<: *trilogy
    database: lobsters_test
  cache:
    <<: *sqlite3
    database: tmp/cache/cache.sqlite3
    migrations_paths: db/cache_migrate
```

What's even weirder is that it deletes a bunch of lines from `db/cache_schema.rb`; running `git diff`:

```
diff --git db/cache_schema.rb db/cache_schema.rb
index dba56904..8823d611 100644
--- db/cache_schema.rb
+++ db/cache_schema.rb
@@ -1,14 +1,13 @@
+# This file is auto-generated from the current state of the database. Instead
+# of editing this file, please use the migrations feature of Active Record to
+# incrementally modify your database, and then regenerate this schema definition.
+#
+# This file is the source Rails uses to define your schema when running `bin/rails
+# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
+# be faster and is potentially less error prone than running all of your
+# migrations from scratch. Old migrations may fail to apply correctly if those
+# migrations use external dependencies or application code.
+#
+# It's strongly recommended that you check this file into your version control system.

 ActiveRecord::Schema[8.0].define(version: 1) do
-  create_table "solid_cache_entries", force: :cascade do |t|
-    t.binary "key", limit: 1024, null: false
-    t.binary "value", limit: 536870912, null: false
-    t.datetime "created_at", null: false
-    t.integer "key_hash", limit: 8, null: false
-    t.integer "byte_size", limit: 4, null: false
-    t.index ["byte_size"], name: "index_solid_cache_entries_on_byte_size"
-    t.index ["key_hash", "byte_size"], name: "index_solid_cache_entries_on_key_hash_and_byte_size"
-    t.index ["key_hash"], name: "index_solid_cache_entries_on_key_hash", unique: true
-  end
-end
-
diff --git db/schema.rb db/schema.rb
index a17f38c5..828d35cc 100644
--- db/schema.rb
+++ db/schema.rb
@@ -10,8 +10,8 @@
 #
 # It's strongly recommended that you check this file into your version control system.

-ActiveRecord::Schema[8.0].define(version: 2025_01_24_063340) do
-  create_table "action_mailbox_inbound_emails", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
+ActiveRecord::Schema[8.0].define(version: 2025_02_03_223624) do
+  create_table "action_mailbox_inbound_emails", charset: "utf8mb4", collation: "utf8mb4_general_ci", force: :cascade do |t|
     t.integer "status", default: 0, null: false
     t.string "message_id", null: false
     t.string "message_checksum", null: false
@@ -55,7 +55,7 @@
     t.index ["category"], name: "index_categories_on_category", unique: true
   end

-  create_table "comment_stats", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
+  create_table "comment_stats", charset: "utf8mb4", collation: "utf8mb4_general_ci", force: :cascade do |t|
     t.date "date", null: false
     t.integer "average", null: false
     t.index ["date"], name: "index_comment_stats_on_date", unique: true
```

I don't know if this is one issue or two, really.
Maybe something is wrong in my `database.yml` that I'm just not seeing, so I've accidentally committed a `schema.rb` that is subtly invalid.
