### ISSUE TITLE
Add option to use docker to setup services.

### ISSUE THREAD

**Issue by thomasdziedzic** [lobsters/lobsters#534]
Development should be as close to production as possible.
This would codify what to use in development to ensure consistent versioning and services.

See https://github.com/lobsters/lobsters/issues/529 for example of where this would have benefited to have.

Initial docker-compose.yml file:

```
version: '3'
services:
  db:
    image: mariadb:10.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
```

and config/database.yml to match it:

```
development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_dev
  host: 127.0.0.1
  username: root
  password: password

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_test
  host: 127.0.0.1
  username: root
  password: password
```

Note that I'm using root to avoid setting up proper permissions since the mariadb container only supports setting up 1 database with 1 user and lobsters requires 2 databases created. This is only intended for development anyways.

Also, I followed these instructions: https://docs.docker.com/install/linux/docker-ce/ubuntu/
