### ISSUE TITLE
proposal for hat redesign

### ISSUE THREAD

**Issue by localhostdotdev** [lobsters/lobsters#682]
current:

<img width="71" alt="current" src="https://user-images.githubusercontent.com/47308085/57341968-be86ea00-713c-11e9-99e9-bd07693b3e51.png">

proposal:

<img width="500" alt="proposal black hat" src="https://user-images.githubusercontent.com/47308085/57341906-7c5da880-713c-11e9-8c3f-c68431f3c4b9.png">

source and live render: https://jsbin.com/vakuyibuwi/1/edit?html,output

so, I tried to make it look like an hat, also tried to make it gender-neutral (women's hats have a tendency to be rounders and men's more squared (excluding caps)).

I think black/white is very minimalist and integrates well with the current design, different colors can be trivially added.

there is a connotation with "black hats" so maybe this design could be used:

<img width="200" alt="white hat" src="https://user-images.githubusercontent.com/47308085/57342323-afa13700-713e-11e9-9762-ca079078621b.png">

if the idea of having some different looking hats sounds good I could either just go ahead an make a PR for `application.css`.

if more iterations on the design are needed I could try other things (tweak the roundness, height, maybe brown like currently?, colors, maybe grey?)).

disclaimer: I'm not a proper designer, I'm just trying to make it obvious that it's an hat

**Comment by pushcx** [comment]
Thanks for taking a swing at the design. We've had a few people confused by the abstract representation of a hat.

I don't want to go to a solid black background or heavy outline because it makes the hats the most visually heavy thing on the page - they draw the eye instead of accenting the post. It's great to have people speaking officially on behalf of projects, but I don't want their comments to overwhelm the discussion. I'd like to see them de-emphasized from how prominent they are now, but I'm not a good enough designer to figure out how.

**Comment by halfmanhalfdonut** [comment]
I think the hats look odd mostly because of their color. If it was changed to 
```css
span.hat {
    border-bottom: 6px solid #eaeaea;
    border-radius: 4px;
    padding: 1px 8px;
    vertical-align: super;
    white-space: nowrap;
}

span.hat span.crown,
span.hat a {
    background-color: #f3f3f3;
    color: #aaa;
    text-decoration: none;
}
```

it would look both less emphasized and more inline with the whiteness of the site.
