### ISSUE TITLE
Accessibility and readability

### ISSUE THREAD

**Issue by dreadnip** [lobsters/lobsters#755]
Hi,

I wanted to take a swing at improving the accessibility (good contrast, safer colours, correct attribute usage, etc..) and readability (fonts, font-size, spacing, whitespace use, colours also) of the site. But before I do this I'd like to know if you're open to this idea. If you guys are hard set on the current design then there would be no point.

**Comment by pushcx** [comment]
I'm generally positive about things that make the site easier to read and use, especially to folks using screen readers or other assistive tech (as in the linked issue). But I'm pretty averse to [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality). So the answer is sure, wherever there's a clear justification that a change is an improvement. Sounds like we should start there for specific changes to make sure you don't waste your time.

**Comment by dreadnip** [comment]
I'm not a Ruby dev so sadly I won't be able to contribute to the core functionality of the website anyway. What I can do is help clean up the front-end.

While doing a quick run through of the HTML/CSS I found that while all of it is still valid, improvements could definitely be made. Let's look at the header for example. Right now the structure is this: div > div (floated) > span > a + clearfix div. This could be rewritten to: header (flexbox) > a.

There are small inconstancies throughout the page, like the main list being an ordered list while its order is by definition variable and can change at any time.

Some devs scoff at these things, but having up-to-date, modern and semantically correct HTML is really important imo. I'll put something together for a PR.

**Comment by svintbel** [comment]
As for me it's a good idea what you offer, but without good knowledge of Rails architecture you will face a lot of troubles cause of ruby integrations into HTML and covering actual views by tests.

**Comment by dreadnip** [comment]
> As for me it's a good idea what you offer, but without good knowledge of Rails architecture you will face a lot of troubles cause of ruby integrations into HTML and covering actual views by tests.

That's true. I don't mind setting up a basic Ruby dev environment just so I can play with the site source myself, but I'd have to look into it a bit.

I've done some work on a static HTML snapshot of the homepage and uploaded it to my Github Pages: https://sanderdlm.be/lob/. I've kept the structure and style as close to the original as possible, while still improving on the things I thought could use some love. Does this look like something you guys could get behind?

**Comment by pushcx** [comment]
I see how you've cleaned up the markup, but I don't know how to tell what's unfinished from what's an intentional change here. The spacing of stories is really funky, and the mobile view is very limited. Could you talk through what changes you were making, maybe separate changes to markup, accessibility, and style choices from each other?

**Comment by dreadnip** [comment]
I can see how all of the changes blend together. Problem is that most of them include both markup and style changes. For example this is the header change:
```html

<div id="header">
--
<div id="header">
    <div id="headerleft">
        <a id="l_holder" style="background-color: #570000;"
           href="/" title="Lobsters (Current traffic: 4%)"></a>


        <span class="headerlinks">
            <a href="/" class="cur_url">Lobsters</a>
            <a href="/recent" class="">Recent</a>
            <a href="/comments" class="">Comments</a>
            <a href="/search" class="">Search</a>
        </span>
    </div>

    <div id="headerright">
        <span class="headerlinks">
            <a href="/login" class="">Login</a>
        </span>
    </div>

    <div class="clear"></div>
</div>
```
to:
```html
<header>
    <a class="logo" href="index.html" title="Lobsters (Current traffic: 3%)" aria-label="home"></a>
    <nav>
        <a href="index.html" class="current">Home</a>
        <a href="recent" class="">Recent</a>
        <a href="comments" class="">Comments</a>
        <a href="search.html" class="">Search</a>
    </nav>
    <a href="login.html" class="">Login</a>
</header>
```
There's multiple choices being made here. <header> instead of <div id="header"> because it's semantically correct. <nav> instead of a <span> for semantics but also accessibility (a lot of screen readers have built in functions to jump to the nav element). The clearfix at the bottom is no longer needed because the new version uses flexbox, which makes the html tag obsolete, but only if you also go with the new CSS.

As you can see it's quite a hand-in-hand situation, where you either go all in and update the whole thing (this doesn't have to change anything visually, but you might as well while you're at it), or you do nothing.

**Comment by pushcx** [comment]
I agree that it's valuable to have semantic HTML and that'd be a nice update, but I don't see how that has to include style changes? But again, I don't know what's an intentional style change vs unfinished.

**Comment by dreadnip** [comment]
I understand how my mock-up page can get confusing. I took multiple stylistic choices on that page like adding lines between the the posts and increasing the font-size, because I think those increase readability and thus the UX of the site. If you wanted to you could disregard those changes. 

That said, there's plenty of style changes for semantic purposes, that have close to no visual impact. To build upon my last comment, this is the CSS for the current header HTML.

```css
/* header */

#header {
	font-weight: bold;
	padding: 5px 10px;
	margin-top: 1em;
	margin-bottom: 0.5em;
	line-height: 18px;
}

#headerleft {
	float: left;
}

#l_holder {
	background-position: center;
	float: left;
	display: block;
	width: 16px;
	height: 16px;
	padding: 1px;
	margin-left: 4px;
	margin-right: 11px;
}

#headertitle {
	padding-right: 0.75em;
}
#headertitle a {
	color: #333;
	text-decoration: none;
}

.headerlinks a {
	color: #777;
	text-decoration: none;
	padding-right: 0.75em;
}

#headerright {
	float: right;
	text-align: right;
}

#headerright .headerlinks a {
	padding-right: 0;
	padding-left: 0.75em;
}

#header a.cur_url {
	color: #333;
}

@media only screen and (max-width: 480px) {
	div#header {
		margin: 0;
		padding: 8px 5px;
		background-color: #eee;
		border-bottom: 1px solid #ccc;
	}
	div#headerleft {
		display: inline;
		float: none;
	}
	div#headerright {
		display: inline;
		float: none;
		text-align: left;
		margin-top: 0.25em;
		clear: both;
	}

	.headerlinks a,
	#headerright .headerlinks a {
		padding-right: 0.25em;
		padding-left: 0;
	}
}
```
and this is the Less CSS that goes along with the new HTML I proposed in my last comment
```css
header {
  display: flex;
  align-items: center;
  margin: 1.5rem 0;

  nav {
    flex: 1;
  }

  a {
    font-weight: bold;
    color: @gray;
    text-decoration: none;
  }

  nav * + * {
    margin-left: 1em;
  }

  .logo {
    background-color: #500000;
    background-image: url(../logo.svg);
    background-size: cover;
    display: block;
    width: 1.2rem;
    height: 1.2rem;
    margin-right: 1rem;
  }

  .current {
    color: @dark-gray;
  }

  @media @mobile { margin: 1rem; }
}
```
Afaik, there's no stylistic changes in the output of this code. Besides the increase in font-size I made no changes to how the nav looks, so they both produce the same thing, but the updated version is shorter, easier to read and can be updated easily in the future. That's what I meant with style changes for semantic purposes. Not visual change, just modern CSS.
